apiVersion: v1
data:
  K8S_STATEFUL_SET_NAME: pd
  K8S_STATEFUL_SET_SERVICE_NAME: pd
  K8S_CLUSTERS: gke-1 gke-2
  K8S_CLUSTER: gke-1
  K8S_SEED_CLUSTER: gke-2
  K8S_NUM_REPLICAS: "2"
  K8S_POD_HOSTNAME_PREFIX: pd-
  K8S_POD_HOSTNAME_SUFFIX:  .gke-1.svc.clusterset.local
  K8S_SEED_HOSTNAME_SUFFIX:  .gke-2.svc.clusterset.local
  K8S_INCREMENT_PORTS: "false"
  REPLICATION_PORT: "8989"
  LDAP_PORT: "7389"
  LDAPS_PORT: "7636"
  HTTPS_PORT: "7443"
  PING_CONTAINER_PRIVILEGED: "false"
  ENABLE_INSECURE_REMOTE_EXTENSIONS: "true"
  MAKELDIF_USERS: "1000"
  ORCHESTRATION_TYPE: KUBERNETES
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: baseline/pingdirectory
  SERVER_PROFILE_URL: https://www.github.com/pingidentity/pingidentity-server-profiles.git
  TAIL_LOG_FILES: '""'
kind: ConfigMap
metadata:
  annotations: {}
  namespace: gke-1
  labels:
    role: pingdirectory
  name: sandbox-pd-environment-variables
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: devops-secret
#  namespace: gke-1
#  annotations:
#    ping-devops.user: vitalii_kalinichenko@epam.com
#    ping-devops.app-version: v0.7.3
#type: Opaque
#data:
#  PING_IDENTITY_DEVOPS_USER: dml0YWxpaV9rYWxpbmljaGVua29AZXBhbS5jb20=
#  PING_IDENTITY_DEVOPS_KEY: YzNlMDExYWUtZTc5OC1mZWFjLTExMGQtMjA4NzIwOTIwODM5
#  PING_IDENTITY_ACCEPT_EULA: WUVT
---
apiVersion: v1
kind: Service
metadata:
  namespace: gke-1
  labels:
    role: pingdirectory
  name: pd
spec:
  ports:
  - name: ldaps
    port: 7636
  - name: ssl
    port: 7443
  - name: ldap
    port: 7389
  selector:
    role: pingdirectory
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: pd
  namespace: gke-1
---
apiVersion: v1
kind: Service
metadata:
  namespace: gke-1
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    role: pingdirectory
  name: pd-0
spec:
  clusterIP: None
  ports:
  - name: ldap
    port: 7389
  - name: ldaps
    port: 7636
  - name: replication
    port: 8989
  - port: 7443
    name: https
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: pd-0
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: pd-0
  namespace: gke-1
---
apiVersion: v1
kind: Service
metadata:
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  namespace: gke-1
  labels:
    role: pingdirectory
  name: pd-1
spec:
  clusterIP: None
  ports:
  - name: ldap
    port: 7389
  - name: ldaps
    port: 7636
  - name: replication
    port: 8989
  - port: 7443
    name: https
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: pd-1
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: pd-1
  namespace: gke-1
---
apiVersion: v1
kind: Service
metadata:
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  namespace: gke-1
  labels:
    role: pingdirectory
  name: pd-2
spec:
  clusterIP: None
  ports:
  - name: ldap
    port: 7389
  - name: ldaps
    port: 7636
  - name: replication
    port: 8989
  - port: 7443
    name: https
  publishNotReadyAddresses: true
  selector:
    statefulset.kubernetes.io/pod-name: pd-2
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: pd-2
  namespace: gke-1
---
apiVersion: v1
kind: Service
metadata:
  namespace: gke-1
  labels:
    role: pingdirectory
  name: pd-cluster
spec:
  clusterIP: None
  ports:
  - name: ldap
    port: 7389
  - name: ldaps
    port: 7636
  selector:
    role: pingdirectory
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: pd-cluster
  namespace: gke-1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: gke-1
  labels:
    role: pingdirectory
  name: pd
spec:
  replicas: 2
  selector:
    matchLabels:
      role: pingdirectory
  serviceName: pd-cluster
  template:
    metadata:
      labels:
        role: pingdirectory
      name: pd
    spec:
      nodeSelector: {}
      containers:
      - envFrom:
        - configMapRef:
            name: sandbox-pd-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true
        image: pingidentity/pingdirectory:2104-8.1.0.3
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /preStop.sh
        name: pd
        ports:
        - containerPort: 7636
        - containerPort: 7443
        - containerPort: 7389
      dnsConfig:
        searches:
          - svc.clusterset.local
          - gke1.svc.clusterset.local
          - clusterset.local
#---
#apiVersion: v1
#kind: Service
#metadata:
#  namespace: gke-1
#  labels:
#    role: pingdataconsole
#  name: pingdata
#spec:
#  ports:
#  - name: https
#    port: 8443
#  selector:
#    role: pingdataconsole
#
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  namespace: gke-1
#  labels:
#    role: pingdataconsole
#  name: pingdata
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      role: pingdataconsole
#  template:
#    metadata:
#      labels:
#        role: pingdataconsole
#    spec:
#     containers:
#      - image: pingidentity/pingdataconsole:2104-8.1.0.3
#        name: pingdata
#        ports:
#        - containerPort: 8443